BULK_UPLOAD_URL = "https://www.commcarehq.org/a/{}/importer/excel/bulk_upload_api/"
LIST_CASES_URL = "https://www.commcarehq.org/a/{}/api/v0.5/case/"
CASE_REPORT_URL = "https://www.commcarehq.org/a/{}/reports/case_data/"
APPLICATION_STRUCTURE_URL = "https://www.commcarehq.org/a/{}/api/v0.5/application/"
APPLICATION_STRUCTURE_DEFAULT_TIMEOUT = 4 * 60  # seconds
COMMCARE_PHONE_FIELD = "phone_home"
COMMCARE_CAN_RECEIVE_SMS_FIELD_NAME = "api_phone_home_sms_verification"
COMMCARE_UPLOAD_STATES = dict(missing=-1, not_started=0, started=1, success=2, failed=3)
COMMCARE_UNSET_CAN_SMS_LABEL = "pending"
COMMCARE_CANNOT_SMS_LABEL = "no"
COMMCARE_CAN_SMS_LABEL = "yes"
DOB_FIELD = "dob"
REDCAP_HOUSING_1_FIELD = "housing_1"
REDCAP_HOUSING_2_FIELD = "housing_2"
REDCAP_HOUSING_FIELD = "housing"
REDCAP_HOUSING_OTHER = "other"
EMPTY_PHONE_VALUES = ("", None)
EMPTY_SELECT_VALUES = ("", None)
TWILIO_INVALID_NUMBER_FOR_REGION_CODE = 404
TWILIO_LANDLINE_CODE = "landline"
TWILIO_LOOKUP_URL = "https://lookups.twilio.com/v1/PhoneNumbers"
TWILIO_MOBILE_CODE = "mobile"
TWILIO_VOIP_CODE = "voip"
WHITE_LISTED_TWILIO_CODES = [
    TWILIO_INVALID_NUMBER_FOR_REGION_CODE,
]

# case fields that all cases will have but that will not be returned by the Application
# Structure API endpoint, which is the source of the case type's properties past and
# present.
COMMCARE_DEFAULT_HIDDEN_FIELD_MAPPINGS = {
    # Form is (<source>, <target>)
    ("case_id", "case_id"),
    ("closed", "closed"),
    ("date_closed", "date_closed"),
    ("date_modified", "date_modified"),
    ("domain", "domain"),
    ("id", "id"),
    ("indexed_on", "indexed_on"),
    ("opened_by", "opened_by"),
    ("indices.parent.case_id", "parent_case_id"),
    ("properties.case_type", "case_type"),
    ("properties.closed_by", "closed_by"),
    ("properties.closed_on", "closed_on"),
    ("properties.date_opened", "date_opened"),
    ("properties.doc_type", "doc_type"),
    ("properties.external_id", "external_id"),
    ("properties.indices.patient", "indices.patient"),
    ("properties.modified_on", "modified_on"),
    ("properties.number", "number"),
    ("properties.owner_id", "owner_id"),
    ("resource_uri", "resource_uri"),
    ("server_date_modified", "server_date_modified"),
    ("server_date_opened", "server_date_opened"),
    ("user_id", "user_id"),
}

# For bulk contact upload, these values should be added to each contact, where key
# is the column name, and val is the row val for that column
COMMCARE_DEFAULT_CONTACT_KEY_VALUES = {
    "parent_type": "patient",
    "ooj": "no",
    # `case_id` gets generated by CommCare, but we need to send a key over.
    "case_id": None,
    "parent_relationship_type": "extension",
    "parent_identifier": "parent",
}

# When syncing REDCap to CommCare and some REDCap records are rejected,
# the following define the integration status columns and values that must be
# updated in REDCap for records that are rejected or successfully synced.
REDCAP_RECORD_ID = "record_id"
REDCAP_REJECTED_PERSON = "rejected_person"
REDCAP_SENT_TO_COMMCARE = "sent_to_commcare"
REDCAP_INTEGRATION_STATUS = "integration_status"
REDCAP_INTEGRATION_STATUS_TIMESTAMP = "integration_status_timestamp"
REDCAP_INTEGRATION_STATUS_REASON = "integration_status_reason"
