#!/usr/bin/env python

import argparse
import sys

import phonenumbers
import requests
from sqlalchemy import create_engine

from common import logger, upload_data_to_commcare

TWILIO_LOOKUP_URL = "https://lookups.twilio.com/v1/PhoneNumbers"
COMMCARE_CAN_RECIEVE_SMS_FIELD_NAME = "contact_phone_can_receive_sms"

WHITE_LISTED_TWILIO_CODES = [
    404,
]


class TwilioLookUpError(Exception):
    def __init__(self, message, info):
        super(TwilioLookUpError, self).__init__(message)
        self.info = info


def format_phone_number(raw, region="US"):
    parsed = phonenumbers.parse(raw, region=region)
    return f"+{parsed.country_code}{parsed.national_number}"


def twilio_lookup_phone_number(number, sid, auth_token):
    response = requests.get(
        f"{TWILIO_LOOKUP_URL}/{number}",
        auth=(sid, auth_token),
        params={"Type": "carrier"},
    )
    if response.ok:
        return response.json()["carrier"]["type"]
    elif response.status_code in WHITE_LISTED_TWILIO_CODES:
        return None
    else:
        message = f"Something went wrong looking up number `{number}`."
        info = {
            "twilio_status_code": response.json().get("status_code"),
            "twilio_error_code": response.json().get("code"),
            "twilio_message": response.json().get("message"),
        }
        raise TwilioLookUpError(message, info)


def can_receive_sms(number_type):
    return number_type == "mobile"


def process_phone_number(formatted_number, sid, auth_token):
    return can_receive_sms(
        twilio_lookup_phone_number(formatted_number, sid, auth_token)
    )


# def contact_can_receive_sms_colum_exists(column_name, db_url):
#     query =
#     engine = create_engine(db_url)


def get_unprocessed_contact_phone_numbers(db_url, search_column):
    """"""
    engine = create_engine(db_url)

    # temporarily have `AND TRUE` as placeholder
    # COMMCARE_CAN_RECIEVE_SMS_FIELD_NAME defined at top of file. currently
    # this column not making way into test DB so can't include in query here.
    query = f"""
        SELECT {search_column}, contact_phone_number FROM contact
        WHERE
            contact_phone_number IS NOT NULL
            AND LENGTH(contact_phone_number) > 0
            AND TRUE
    """
    conn = engine.connect()
    try:
        result = conn.execute(query)
        return [dict(row) for row in result.fetchall()]
    finally:
        conn.close()


def main(
    db_url,
    commcare_user_name,
    commcare_api_key,
    commcare_project_name,
    twilio_sid,
    twilio_token,
    search_column,
):
    exit_status = 0
    data = [
        dict(item, **{COMMCARE_CAN_RECIEVE_SMS_FIELD_NAME: None})
        for item in get_unprocessed_contact_phone_numbers(db_url, search_column)
    ]
    formatted = []
    for item in data:
        try:
            item["contact_phone_number"] = format_phone_number(
                item["contact_phone_number"]
            )
            formatted.append(item)
        except phonenumbers.NumberParseException:
            logger.warning(
                f"The number `{item['contact_phone_number']}` for contcact "
                f"`{item[search_column]}` cannot be parsed and will not be further "
                f"processed."
            )
    twilio_processed = []
    exit_status = 0
    try:
        for item in formatted:
            processed = process_phone_number(
                item["contact_phone_number"],
                twilio_sid,
                twilio_token,
            )
            if processed:
                item[COMMCARE_CAN_RECIEVE_SMS_FIELD_NAME] = processed
                twilio_processed.append(item)
            else:
                logger.warning(
                    f"Phone number `{item['contact_phone_number']}` for contact with "
                    f"ID {item['id']} could not be processed by Twilio. Moving on."
                )
    except Exception as exc:
        logger.error(f"Something unexpected happened: {exc.message}")
        exit_status = 1
    finally:
        if twilio_processed:
            logger.info(
                f"Will attempt to upload the {len(twilio_processed)} numbers "
                f"successfully processed by Twilio to CommCare."
            )
            # prep for export. contact_phone_number is already in db and we don't need
            # to send it again.
            for item in twilio_processed:
                del item["contact_phone_number"]
            upload_data_to_commcare(
                twilio_processed,
                commcare_project_name,
                "contact",
                search_column,
                commcare_user_name,
                commcare_api_key,
                "off",
            )
    sys.exit(exit_status)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--db",
        help="The db url string of the db that contains contact data",
        dest="db_url",
    )
    parser.add_argument(
        "--username",
        help="The Commcare username (email address)",
        dest="commcare_user_name",
    )
    parser.add_argument("--apikey", help="A Commcare API key", dest="commcare_api_key")
    parser.add_argument(
        "--project", help="The Commcare project name", dest="commcare_project_name"
    )
    parser.add_argument(
        "--twilioSID", help="The SID of a Twilio account", dest="twilio_sid"
    )
    parser.add_argument(
        "--twilioToken", help="Auth token for the Twilio account", dest="twilio_token"
    )
    parser.add_argument(
        "--searchColumn",
        help="The column in db that will be matched as ID against Commcare's ID",
        dest="search_column",
        default="id",
    )
    args = parser.parse_args()
    main(
        args.db_url,
        args.commcare_user_name,
        args.commcare_api_key,
        args.commcare_project_name,
        args.twilio_sid,
        args.twilio_token,
        args.search_column,
    )
